name: RSS â†’ Telegram (Go)

on:
  schedule:
    - cron: "*/30 * * * *"   # every 10 minutes (UTC)
  #workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Run RSS bot
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHANNEL_ID: ${{ secrets.TG_CHANNEL_ID }}
          GEMINI_API_TOKEN: ${{ secrets.GEMINI_API_TOKEN }}
          GEMINI_MODEL: ${{ secrets.GEMINI_MODEL }}
        run: go run main.go

      - name: Save state
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add state.json
          git commit -m "Update RSS state" || echo "No changes"
          git push
